### ISSUE TITLE
Start building a woordje community 

### ISSUE THREAD

**Issue by jellevervloessem** [TimBroddin/woordje.be#2]
There's lots of fuzz about wordle, but I can't find any Dutch communities. 

I already created a subreddit: https://www.reddit.com/r/woordje?utm_medium=android_app&utm_source=share

Maybe the next thing can be a discord server. (let's wait and see if reddit is used...) 

Can you add it to the winning screen?

**Comment by TimBroddin** [comment]
I've added this (both on home & winning screen). Let's see if this manages to take off :)

**Comment by jellevervloessem** [comment]
Whaw what a surprise this morning 🤩

**Comment by TimBroddin** [comment]
het doet niet veel he :)

**Comment by jellevervloessem** [comment]
klopt :-) van mij mag dat weg ze, kheb het gevoel dat reddit ook niet zo leeft onder de Woordjes zoekers.
